# Generated by Django 4.0 on 2023-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_Active',
            field=models.BooleanField(default=False),
        ),
    ]
